# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Cathy Hou
title: Harvard Senior (May 2026) — Computer Science & Statistics
email: cathyhou@college.harvard.edu
website: https://cathy-h-04.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  cathy-h-04
linkedin_username: https://www.linkedin.com/in/cathy-hou-29889a1b7/

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  I'm a senior at Harvard studying Computer Science & Statistics.
  I have a strong interest in systems, networking, and high-performance programming. Demonstrated experience with distributed systems and performance optimizations applied to machine learning and AI workloads. Excited to work @ intersection of ML and Systems!

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Smart Student Model
        link: https://github.com/cathy-h-04/smart-student-model
        link_text: GitHub
        additional_links: []
        quote: "Automated validation of multilingual MCQs using context-aware NLP models"
        description: |
          Built a system to evaluate the quality of reading comprehension multiple-choice questions (MCQs) 
          in English and Portuguese using the Pirá 2.0 dataset. Trained and compared context-sensitive 
          and context-agnostic models to detect whether questions require passage understanding. 
          Helps educators identify and fix poor-quality assessment items.
            content:
      - layout: left
        title: KonkurrentKruskal
        link: 
        link_text: GitHub
        additional_links: []
        quote: "A parallelized Kruskal's alg. with shared+distributed memory at 30% speedup per processor"
        description: |
          Re-engineered Kruskal's algorithm for urban infrastructure planning by integrating OpenMP and MPI parallelism. 
          Built a hybrid model to construct local MSTs, apply parallel radix sorting, and reduce serial edge processing. 
          Demonstrated significant runtime speedups for large-scale logistics and transportation graphs.
      - layout: left
        title: Differential Privacy Tool
        link: https://github.com/cathy-h-04/differential-privacy-tool
        link_text: GitHub
        additional_links: []
        quote: "Tool for privacy-preserving data analysis"
        description: |
          Developed a full-stack web app with a Flask backend and React/Tailwind frontend to demonstrate 
          differential privacy techniques. Includes a privacy playground for experimenting with mechanisms, 
          a form that locally privatizes user input before submission, and personalized DP query execution 
          with epsilon-based row-level filtering. Also implements data shuffling for aggregator privacy.
      - layout: left
        title: Podcast Machine
        link: https://github.com/cathy-h-04/podcast-machine
        link_text: GitHub
        additional_links:
          - title: Example Script
            icon: fas fa-file-alt
            url: https://github.com/cathy-h-04/podcast-machine/blob/main/example_script.txt
        quote: "LLM-powered tool that transforms PDFs into voice-narrated podcasts with auto-generated cover art"
        description: |
          Built an AI system that takes PDFs or research topics and generates multi-voice podcast episodes. 
          Uses Claude AI for script generation, Cartesia TTS for realistic speaker voices, and Stable Diffusion 
          for dynamic cover art. Features custom podcast formats (e.g., debate, interview), a professional-grade 
          audio player, and Tavus API integration for video-based podcast discussion.
      - layout: left
        title: Deep Space X11-Proxy (NASA JPL)
        quote: "X11/TCP proxy for synchronized remote GUIs"
        description: |
          Built a TCP-based X11 proxy to render synchronized Deep Space Network GUIs
          across remote displays. Enabled command-control switching via sync techniques
          and ensured session persistence with long-term state storage.

- title: Experience
  layout: list
  content:
    - layout: right
      title: Amazon
      sub_title: Software Engineering Intern
      caption: June 2025 to Present
      quote: >
        Built an intelligent agent to query multi-source deployment data at scale.
      description: |
        - Built a chatbot to analyze deployment and validation data from PostgreSQL+DynamoDB  
        - Deployed a serverless backend (AWS Lambda, API Gateway, CDK) supporting 1,000+ requests/sec  
        - Created an MCP-style agent to construct, execute, and explain queries, cutting lookup time by 80%  
        - Integrated RAG, prompt engineering, and orchestration workflows

    - layout: right
      title: NASA Jet Propulsion Laboratory
      sub_title: Software Engineering Intern
      caption: June 2024 to Aug 2024
      quote: >
        Networked GUI control over the Deep Space Network using X11/TCP protocol.
      description: |
        - Duplicated X client interfaces to multiple X servers for remote GUI rendering  
        - Implemented synchronized GUI command switching across remote displays  
        - Designed proxy X servers to intercept and analyze client streams  
        - Enabled state-preserving user sessions with long-term storage features

    - layout: right
      title: Harvard University
      sub_title: CS51 Head Teaching Fellow, CS50 Course Assistant
      caption: Aug 2023 to Present
      description: |
        - Taught recursion, memory management, and formal semantics  
        - Led sections, office hours, and wrote unit tests
        - 1/200+ students selected from class to serve as Head Teaching Fellow

    - layout: right
      title: Alaska Center for Energy and Power
      sub_title: NSF CS Intern
      caption: June 2023 to Nov 2023
      description: |
        - Developed a synthetic power grid model of a remote Alaskan town  
        - Built a forecasting website for renewable energy adoption  
        - Presented at NAPS, submitted to IEEE
  - title: Education
    layout: list
    content:
        - layout: top-right
          title: Harvard University
          sub_title: B.A. in Computer Science and Statistics
          caption: Aug 2022 to May 2026 (expected)
          quote: >
            Focus on systems, machine learning, and statistical modeling
          description: | # this will include new lines to allow paragraphs
            Relevant Coursework:
              Abstraction+Design in Computation
              Systems Programming
              Artificial Intelligence
              Computer Graphics
              Data Science
              Advanced Data Science
              Algorithms + Limitations
              Data Structures
              High-Performance Computing
              Systems Security
              Differential Privacy
              Distributed Systems (MIT)
              Linear Algebra
              Multivariable Calculus
              Probability
              Statistical Inference
              Privacy+Tech
              Discrete Math

  - title: Extracurriculars + Interests
    layout: text
    content: | # this will include new lines to allow paragraphs
      **Social Impact Work**  
      Created an AI-based chatbot to help low-income families access social services through OneDegree, a non-profit resource directory. The project was featured in [OneDegree's blog](https://about.1degree.org/exploring-ais-potential-in-social-services-harvard-x-one-degree/), highlighting the use of natural language models to improve equity in resource access.

      **Environmental Work**
      - Advised $150M+ impact fund on solar home system expansion in Sub-Saharan Africa through Harvard Consulting for Business and the Environment   
      - Created financial simulation game and green energy strategy tools for nonprofits through Tech for Social Good  
      - Led research on EU treaty reforms for energy autonomy; presented to Czech government via Harvard Foreign Policy Initiative  
      - Consulted solar startup SYSO Technologies on energy legislation and market entry as part of Harvard Clean Energy Group

      **Leadership**  
      Director of Professional Development of Harvard Computer Society, Case Team Leader of Harvard Data Analytics Group, Senior Software Engineer of Tech for Social Good. Engaged in mentoring and career opportunities, tech-for-social-good initiatives, and research discussions around NLP and data privacy.

      **Interests**  
      Passionate about privacy-preserving AI, real-time systems, and environment. Outside of academics, I enjoy birdwatching and hiking!

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
