# Site
repository: cathy-h-04/cathy-h-04.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Cathy Hou
title: Harvard Senior (May 2026) — Computer Science & Statistics
email: cathyhou@college.harvard.edu
website: https://cathy-h-04.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  cathy-h-04
linkedin_username: https://www.linkedin.com/in/cathy-hou-29889a1b7/

# Additional icon links
additional_links:
- title: Link name
  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a senior at Harvard studying Computer Science & Statistics.
  I have a strong interest in systems, networking, and high-performance programming. Demonstrated experience with distributed systems and performance optimizations applied to machine learning and AI workloads. Excited to work @ intersection of ML and Systems!

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: Smart Student Model
        link: https://github.com/cathy-h-04/smart-student-model
        link_text: GitHub
        quote: "Automated multilingual MCQ validation using context-aware NLP models"
        description: |
          Built a system to evaluate the quality of reading comprehension multiple-choice questions (MCQs) in **English** and **Portuguese** using the `Pirá 2.0` dataset.  
          Trained and compared `context-sensitive` vs. `context-agnostic` models to detect passage-dependence, helping educators identify low-quality assessment items.

      - layout: left
        title: KonkurrentKruskal
        quote: "Parallelized Kruskal's algorithm with shared + distributed memory • ~30% speedup per processor"
        description: |
          Re-engineered Kruskal's algorithm using **OpenMP** and **MPI** for urban infrastructure planning.  
          Constructed local MSTs, applied parallel hyper QuickSort, and optimized edge filtering.  
          Achieved significant runtime improvements on large-scale logistics graphs.

      - layout: left
        title: Differential Privacy Tool
        link: https://github.com/cathy-h-04/differential-privacy-tool
        link_text: GitHub
        quote: "Interactive privacy playground for exploring differential privacy"
        description: |
          Developed a full-stack app (**Flask** + **React/Tailwind**) to demo differential privacy techniques:  
          - **Privacy playground** for experimenting with noise mechanisms  
          - Form input → **local privatization** before submission  
          - **Personalized DP queries** with ε based row filtering  
          - **Data shuffling** to protect aggregated records

      - layout: left
        title: Podcast Machine
        link: https://github.com/cathy-h-04/podcast-machine
        link_text: GitHub
        additional_links:
          - title: Example Script
            icon: fas fa-file-alt
            url: https://github.com/cathy-h-04/podcast-machine/blob/main/backend/example_script.txt
        quote: "LLM-to-audio pipeline that transforms PDFs into narrated podcast episodes"
        description: |
          Built an AI system to convert research PDFs into podcast episodes using:  
          - `Claude AI` for **multi-voice script generation**  
          - `Cartesia TTS` for voice cloning  
          - `Stable Diffusion` for auto-generated cover art  
          Supports debate/interview formats and includes **Tavus** video integration.

      - layout: left
        title: Deep Space X11 Proxy (NASA JPL)
        quote: "X11/TCP proxy for synchronized GUI control over the Deep Space Network"
        description: |
          Developed a TCP-based `X11` proxy to duplicate and synchronize Deep Space Network GUIs across remote displays.  
          Enabled real-time command control switching and implemented **session persistence** with durable state storage.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: Amazon
        sub_title: Software Engineering Intern
        caption: June 2025 to Present
        quote: "Built a conversational agent for querying deployment data"
        description: |
          - Built a chatbot to analyze deployment and validation data from `PostgreSQL` + `DynamoDB`  
          - Deployed a serverless backend using **AWS Lambda**, **API Gateway**, **CDK**  
          - Created an intelligent agent to automate complex queries, reducing lookup time by 80%  
          - Integrated **RAG**, prompt engineering, and microservices orchestration

      - layout: right
        title: NASA Jet Propulsion Laboratory
        sub_title: Software Engineering Intern
        caption: June 2024 to Aug 2024
        quote: "X11/TCP GUI multiplexing across deep-space command terminals"
        description: |
          - Deployed proxy `X11` servers for real-time GUI mirroring  
          - Enabled synchronized command switching across distributed displays  
          - Built session state storage for **resilient user continuity**

      - layout: right
        title: Harvard University
        sub_title: CS51 Head Teaching Fellow, CS50 Course Assistant
        caption: Aug 2023 to Present
        description: |
          - Led sections on **recursion**, memory management, and formal semantics  
          - Hosted office hours, wrote unit tests, and mentored TAs  
          - Selected from 200+ students as **Head Teaching Fellow**

      - layout: right
        title: Alaska Center for Energy and Power
        sub_title: NSF Computer Science Intern
        caption: Jun 2023 to Nov 2023
        description: |
          - Modeled synthetic **power grids** for remote Alaskan towns  
          - Built a forecasting dashboard for renewable energy transitions  
          - Presented findings at **NAPS**; submitted work to **IEEE**

  - title: Education
    layout: list
    content:
      - layout: top-right
        title: Harvard University
        sub_title: B.A. Computer Science & Statistics
        caption: Aug 2022 to May 2026 (expected)
        quote: "Systems, ML, & statistical modeling focus"
        description: |
          **Relevant Coursework:**  
          `Abstraction + Design in Computation` • `Systems Programming` • `Artificial Intelligence`  
          `Computer Graphics` • `Data Science` • `Advanced Data Science` • `Algorithms` • `Data Structures`  
          `High-Performance Computing` • `Systems Security` • `Distributed Systems` • `Differential Privacy`  
          `Linear Algebra` • `Multivariable Calculus` • `Probability` • `Statistics` • `Privacy + Tech` • `Discrete Math`

  - title: Extracurriculars + Interests
    layout: text
    content: |
      **Social Impact Work**  
      Built an AI chatbot for `OneDegree`, a nonprofit aiding low-income families — featured in [OneDegree’s blog](https://about.1degree.org/exploring-ais-potential-in-social-services-harvard-x-one-degree/).

      **Environmental Work**  
      - Advised $150M+ solar fund via **HCBE** on Sub-Saharan Africa expansion  
      - Developed green energy tools via **Tech for Social Good**  
      - Presented EU energy research to Czech government via **FPI**  
      - Consulted solar policy for **Harvard Clean Energy Group**

      **Leadership**  
      Director of Professional Development @ **Harvard Computer Society** •  
      Case Team Lead @ **Harvard Data Analytics Group** •  
      Senior Software Engineer @ **Tech for Social Good**

      **Interests**  
      Passionate about *privacy-preserving AI*, real-time systems, and sustainability.  
      I enjoy `birdwatching`, `hiking`, and mentoring aspiring engineers.


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
